#ifndef SIMPLEANIMATIONPLUGIN_GLOBAL_H
#define SIMPLEANIMATIONPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMPLEANIMATIONPLUGIN_LIBRARY)
#  define SIMPLEANIMATIONPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIMPLEANIMATIONPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLEANIMATIONPLUGIN_GLOBAL_H
